name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
         
          git remote rm hf || true
          
          
          cd ..
          rm -rf hf_deploy
          mkdir hf_deploy
          
         
          rsync -av --exclude='.git' QGen-AI/ hf_deploy/
          
          
          cd hf_deploy
          git init -b main
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          
          
          git add .
          git commit -m "deploy: production release asset compilation"
          
          
          git remote add hf https://eadey:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/eadey/QGen-AI
          git push hf main --force